language: node_js
sudo: required
addons:
  chrome: stable
node_js:
  - "12"
before_install:
  - npm i npm@^6 -g
install:
  - npm install
script:
  - npm test
  - npm run build
services:
  - xvfb
notifications:
  email: false
